# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-03 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20170103_0326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_data',
            name='image',
            field=models.ImageField(upload_to='/media/images_pi/,default="/media/images_pi/default.png"'),
        ),
    ]
